<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

Subsetting: To select one or more elements from a list or array.

Indexing: To select an element from a list or array.

Slicing: To select a range of elements from a list or array.

Masking: To select elements that are 'True' to a condition from an array.

In [1]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
np_array_number = np_array_2d[:,0] #to extract all the numbers out as the numbers are index 0 in the sub-list
np_array_int = np_array_number.astype(int) #numpy array will change all elements into char so need to convert the numbers into int for maths operation
np_array_int_odd = np_array_int % 2 != 0 #to find odd number
print(np_array_2d[np_array_int_odd, 1]) #to exctract odd number's alphabet

['A' 'C' 'E' 'G' 'I']


In [7]:
array_2d = np.array([[66, 50, 57, -1, -1],
                     [92, -1, 88, -1, -1],
                     [75, -1, -1, 76, -1],
                     [-1, 51, 87, -1, -1],
                     [71, -1, 67, -1, 69]])
array_less50 = array_2d < 50 #extract elements that are less than 50
array_more50 = array_2d > 50
array_equal50 = array_2d == 50 
array_2d[array_less50] = -1 #converting elements in main list
array_2d[array_more50] = 1
array_2d[array_equal50] = 0
print(array_2d)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
